name: FMAR New Requirement / Change Proposal
description: Propose a new requirement for FMAR or a significant change to existing design.
title: "[PROPOSAL] Short descriptive title of the proposal"
labels: ["type:proposal", "status:triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the FMAR design! Use this template to propose new requirements or significant changes.
  - type: input
    id: affected-area
    attributes:
      label: Area of FMAR Affected
      description: "e.g., Asset Registration (ARM), FSP Onboarding (SPUM), API Design, Data Model for X, PSQM Concept, GICM Concept"
      placeholder: "Specify FMAR module or design area"
    validations:
      required: true
  - type: textarea
    id: current-problem
    attributes:
      label: Description of the Current Situation / Problem
      description: What is the issue, gap, or opportunity your proposal aims to address?
      placeholder: "Describe the context..."
    validations:
      required: true
  - type: textarea
    id: detailed-proposal
    attributes:
      label: Detailed Proposal
      description: "Describe your proposed new requirement or change. Include your rationale and the expected benefits to the FMAR system or its users."
      placeholder: "Detail your proposal here..."
    validations:
      required: true
  - type: textarea
    id: use-cases-supported
    attributes:
      label: Use Case(s) Supported (If applicable)
      description: How would this proposal enable or improve specific FMAR use cases (either MVP or future vision)?
      placeholder: "e.g., Improves efficiency of asset registration for large portfolios by..."
    validations:
      required: false
  - type: textarea
    id: potential-impacts
    attributes:
      label: Potential Impacts / Dependencies (If known)
      description: Are there other parts of FMAR, external systems (DSI, Dispatch API), or existing processes this might impact?
      placeholder: "e.g., May require changes to the FMAR Common Ontology, depends on DSI capability X..."
    validations:
      required: false
  - type: input
    id: organisation-role-proposal
    attributes:
      label: Your Organisation/Role (Optional, for context)
      description: "e.g., FSP - Large Generator, DSO - Innovation Lead, Tech Vendor"
      placeholder: "Your Organisation Name / Your Role"
    validations:
      required: false
